export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_DARK_MODE = "SET_DARK_MODE";
export const SET_CURRENT_COUNTRY = "SET_CURRENT_COUNTRY" ;
export const SET_PAGE_TITLE = "SET_PAGE_TITLE" ;
export const SET_PAGE_DESCRIPTION= "SET_PAGE_DESCRIPTION" ;